name: Property CI
on: #[push, pull_request]
  - push:
      - "property/**"
      - ".github/workflows/property-workflow.yml"
  - pull_request:
      - "property/**"
      - ".github/workflows/property-workflow.yml"

jobs:
  pipeline:
    name: property pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
    steps:
      - name: Locating property microservice directory
        run: cd property
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Run backend test
        run: |
          chmod +x mvnw
          npm run ci:backend:test
      - name: Package application
        run: npm run java:jar:prod
